global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "atlas-node-1"
    static_configs:
      - targets: ["host.docker.internal:9001"]
        labels:
          node_id: "1"

  - job_name: "atlas-node-2"
    static_configs:
      - targets: ["host.docker.internal:9002"]
        labels:
          node_id: "2"

  - job_name: "atlas-node-3"
    static_configs:
      - targets: ["host.docker.internal:9003"]
        labels:
          node_id: "3"

  - job_name: "atlas-node-4"
    static_configs:
      - targets: ["host.docker.internal:9004"]
        labels:
          node_id: "4"
