[package]
name = "atlas-mempool"
version = "0.1.0"
edition = "2024"

[dependencies]
atlas-common = { path = "../atlas-common" }
tokio = { workspace = true }
tracing = { workspace = true }
sha2 = "0.10"
hex = { workspace = true }
ed25519-dalek = { workspace = true }
